# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: true
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_version: 17.0
org_name: OpenG2P
org_slug: OpenG2P
rebel_module_groups: []
repo_description: This repo is contains modules used by OpenG2P for Notifications
repo_name: OpenG2P Notifications
repo_slug: openg2p-notifications
repo_website: https://github.com/OpenG2P/openg2p-notifications
travis_apt_packages: []
travis_apt_sources: []

